### ISSUE TITLE
Надо пользователя как-то уведомлять, а то он будет думать, что приложение "глючит"

### ISSUE THREAD

**Issue by coursar** [aygulmardanova/task-tracker#3]
https://github.com/aygulmardanova/task-tracker/blob/432bd15feb555120120fbaccbc569c6bf03b48ee/src/js/widgets.js#L36-L39

**Comment by aygulmardanova** [comment]
Не поняла.. Каким-то окошком сделать? Далее ведь эта запись исчезает
Или сделать так, чтобы исчезала при изменении поля ввода?

**Comment by coursar** [comment]
Всё ок.
